language: php
sudo: false
dist: trusty

addons:
  apt_packages:
    - ldap-utils
    - slapd

env:
  global:
    - RUN_PHPCS="no"
    - COMPOSER_FLAGS="--prefer-stable"

matrix:
  fast_finish: true
  include:
    # The Trusty build does not support PHP 5.3
    - php: 5.3
      dist: precise
    - php: 5.3
      env: COMPOSER_FLAGS="--prefer-stable --prefer-lowest"
      dist: precise
    - php: 5.4
    - php: 5.5
    - php: 5.6
      env: RUN_PHPCS="yes"
    - php: 7.0
    - php: 7.0
      # This empty flag removes the prefer-stable switch to cause dev dependencies to be installed
      env: COMPOSER_FLAGS=""
    - php: 7.1
    - php: 7.2
    - php: nightly
  allow_failures:
    - php: 7.2
    - php: nightly

before_install:
  - mkdir /tmp/slapd
  - slapd -f .travis/ldap/conf/slapd.conf -h ldap://localhost:3389 &
  # This sleep is required to ensure the slapd process is running before loading the data in
  - sleep 3
  - ldapadd -h localhost:3389 -D cn=admin,dc=joomla,dc=org -w joomla -f .travis/ldap/data/base.ldif
  - ldapadd -h localhost:3389 -D cn=admin,dc=joomla,dc=org -w joomla -f .travis/ldap/data/fixtures.ldif

before_script:
  # The Trusty build is compiled with LDAP support
  - if [[ $TRAVIS_PHP_VERSION = 5.3 ]]; then phpenv config-add .travis/phpenv/ldap.ini; fi
  - composer self-update
  - composer update $COMPOSER_FLAGS

script:
  - vendor/bin/phpunit
  - if [ "$RUN_PHPCS" == "yes" ]; then vendor/bin/phpcs --config-set installed_paths vendor/joomla/coding-standards && vendor/bin/phpcs -p --report=full --extensions=php --standard=ruleset.xml src/; fi;
